version: '3.12'

networks:
  kcx-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db-redis
      - db-sqlite3
    networks:
      - kcx-network
    volumes:
      - ./database:/app/database
      - ./data:/app/data 
    environment:
      - IS_IN_KCX_BACKEND_DOCKER=TRUE

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - kcx-network

  db-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - kcx-network

  db-sqlite3:
    image: "nouchka/sqlite3"
    volumes:
      - ./database:/data  # Mount the host directory to persist the SQLite files
    ports:
      - "8080:8080"
    networks:
      - kcx-network
