# Dockerfile for Svelte frontend

FROM node:16
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend .
COPY frontend/certs/example_local_cert.pem /app/certs/example_local_cert.pem
COPY frontend/certs/example_local_key.pem /app/certs/example_local_key.pem

# Expose the port the dev server runs on
EXPOSE 5173

# Command to run the app in development mode
CMD ["npm", "run", "dev", "--", "--host"]
